# Generated by Django 4.1.7 on 2023-09-30 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('referal_code', models.CharField(max_length=10)),
                ('people_joined', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
